import { Product } from '@prisma/client'
import Head from 'next/head'
import { MagnifyingGlass, Plus } from 'phosphor-react'
import { FormEvent, useState } from 'react'
import { Box } from '../components/design-system/Box'
import { Button } from '../components/design-system/Button'
import { Heading } from '../components/design-system/Heading'
import {Text} from "../components/design-system/Text"
import { TextInput } from '../components/design-system/TextInput'
import { Container, FormControl, ItensContainer } from '../styles/home'
import { Incoming } from '../types/Incoming'




export default function Home() {
 
  const [incoming, setIncoming] = useState<Incoming>({
    id: 0,
    products: [],
    supplier: {
    id: 0,
  name: "teste",},
  value: 0
  })


  interface ProductForm {
    name: string,
    value: number,
  }
    const [product, setProduct] = useState<ProductForm>({
      name: "",
      value: 0
    })

    function onAddButtonClick () {
      setIncoming({
        ...incoming, products: [...incoming.products, {...product}]
      })
    }

    function onSubmit (event: FormEvent<HTMLFormElement>){
      event.preventDefault()
      console.log(incoming)
    }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />        
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Box>
          <Heading>Cadastro</Heading>
          <form onSubmit={onSubmit}>       
          <FormControl>
          <TextInput placeholder='Forcenedor' value={incoming.supplier.id} onChange={e => setIncoming({...incoming, supplier: {...incoming.supplier, id: Number(e.target.value)}})}/>
          <Text>{incoming.supplier.name}</Text>          
          <Button type='button' variant='secondary'><MagnifyingGlass/></Button>
          </FormControl>
          <FormControl>
          <TextInput placeholder='Produto' value={product.name} onChange={e => setProduct({...product, name: e.target.value})}/>
          <TextInput placeholder='Valor' value={product.value} onChange={e => setProduct({...product, value: Number(e.target.value)})}/>
          <Button type='button' onClick={onAddButtonClick}><Plus/></Button>
          </FormControl>
          <Button>Enviar</Button>  
          <Box>
            <ItensContainer>
             {incoming.products.length> 0 ?
             incoming.products.map((product, index) => (<Text key={index}>{product.name} - {product.value}</Text>)) : <span>Adcione um item</span>}
           </ItensContainer>
          </Box>
          </form>         
        </Box>
      </Container>
    </>
  )
}
