import Head from 'next/head'
import { Button } from '../components/design-system/Button'
// import { Inter } from '@next/font/google'


// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />        
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Button>teste</Button>
      </main>
    </>
  )
}
